version: '3.2'

networks:
  tn:
    driver: bridge

volumes:
  server_nm:
    driver: local

services:
  api:
    build: ./
    container_name: api
    ports:
      - "3009:3009"
    volumes:
      - "./:/app"
      - "server_nm:/app/node_modules"
      - "./.env.production:/app/.env"
    networks:
      - tn
    command: ["sh", "-c", "npm run start"]
